version: "3"

networks:
  sm-net:
    external: true

services:
  dashboard:
    image: sentinel-dashboard:1.7.0
    environment:
    - sentinel.dashboard.nacos.config.server-addr=nacos
    - sentinel.dashboard.nacos.config.namespace=4c33f46c-fd59-4c27-b725-14c7af59fed8
    volumes:
    - /opt/sentinel/logs/:/root/logs
    - /opt/sentinel/heap_dump:/heap_dump
    ports:
    - "8090:8080"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
    - sm-net