filebeat.inputs:
# 仅收集镜像名称包含 imageName 的APP容器日志
- type: container
  paths:
  - "/var/lib/docker/containers/*/*-json.log"
  #- "/var/log/containers/*.log"
  # 是否从文件末尾开始收集日志
  tail_files: true
  # 将error日志合并到一行
  multiline.pattern: '^\\d{2}:\\d{2}:\\d{2}'
  multiline.negate: true
  multiline.match: after
  multiline.timeout: 10s
  # APP 专有处理器
  processors:
  - drop_event:
      when.not.contains:
        container.image.name: "imageName"
# 仅收集 stack 是 EFK 的容器日志
- type: container
  paths:
  - "/var/lib/docker/containers/*/*-json.log"
  #- "/var/log/containers/*.log"
  # 是否从文件末尾开始收集日志
  tail_files: true
  # 将error日志合并到一行
  multiline.pattern: '^(\{|\[|\\d{4}-\\d{2}-\\d{2})'
  multiline.negate: true
  multiline.match: after
  multiline.timeout: 10s
  # EFK 专有的处理器
  processors:
  - drop_event:
      when.not.equals:
        container.labels.com_docker_stack_namespace: "efk"
# 收集其他 非EFK、非APP 的容器日志
- type: container
  paths:
  - "/var/lib/docker/containers/*/*-json.log"
  #- "/var/log/containers/*.log"
  # 是否从文件末尾开始收集日志
  tail_files: true
  # 将error日志合并到一行
  multiline.pattern: '^(\{|\[|\w)'
  multiline.negate: true
  multiline.match: after
  multiline.timeout: 10s
  # 专有的处理器
  processors:
  - drop_event:
      when.or:
        - equals:
            container.labels.com_docker_stack_namespace: "efk"
        - contains:
            container.image.name: "imageName"

# 通用配置
#filebeat.registry_file: /usr/share/filebeat/registry

# 公共的处理器
processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"
- drop_fields:
    fields: ["stream", "log", "input", "ecs", "agent"]

#==================== Elasticsearch template setting ==========================
setup.template.name: "filebeat"
setup.template.fields: "filebeat.template.json"
setup.template.overwrite: true
setup.template.enabled: false

#-------------------------- Elasticsearch output ------------------------------
# 直接输出到elasticsearch,这里的hosts是elk地址，端口号是elasticsearch端口#
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
#  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  index: "filebeat-%{+yyyy.MM.dd}"
  indices:
    - index: "imageName-%{+yyyy.MM.dd}"
      when.contains:
        container.image.name: "imageName"
    - index: "efk-%{+yyyy.MM.dd}"
      when.equals:
        container.labels.com_docker_stack_namespace: "efk"
    - index: "image-%{+yyyy.MM.dd}"
      when.and:
      - not.equals:
          container.labels.com_docker_stack_namespace: "efk"
      - not.contains:
          container.image.name: "imageName"
      - has_fields: ['container.id']