version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.3.1
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      #- bootstrap.memory_lock=true
      # 测试开发时开启此配置，避免磁盘告警导致无法启动
      - cluster.routing.allocation.disk.threshold_enabled=false
      # 集群名称
      - cluster.name=efk-cluster
      # 节点名称
      - node.name=elasticsearch
      # cluster.initial_master_nodes 和 discovery.zen.ping.unicast.hosts 二选一
      # 初始主节点，多个节点以英文逗号分隔
      - cluster.initial_master_nodes=elasticsearch
      #- discovery.zen.ping.unicast.hosts=elasticsearch
      # 开启http访问
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    volumes:
      - /opt/efk/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - efk-net
    deploy:
      mode: replicated
      replicas: 1
#      resources:
#        limits:
#          memory: 1g
      placement:
        constraints:
          - node.labels.elasticsearch == 1

  kibana:
    image: kibana:7.3.1
    volumes:
#      - /opt/efk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /opt/efk/kibana/data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_REQUESTTIMEOUT=90000
      - XPACK_SECURITY_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - cluster.name=efk-cluster
    ports:
      - 5601:5601
    networks:
      - efk-net
    depends_on:
      - elasticsearch
        
#  filebeat:
#    image: prima/filebeat:6
#    volumes:
#      - /opt/efk/filebeat/config/filebeat.yml:/filebeat.yml
#      - /opt/efk/filebeat/data:/data
#      - /var/lib/docker/containers:/var/lib/docker/containers
#    networks:
#      - efk-net
#    deploy:
#      mode: global
#      restart_policy:
#        condition: on-failure
#        delay: 30s

  filebeat:
    image: elastic/filebeat:7.3.1
    command: filebeat
    volumes:
    - /opt/efk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    - /opt/efk/filebeat/data:/usr/share/filebeat/data
    - /opt/efk/filebeat/logs:/usr/share/filebeat/logs
    #- /opt/efk/filebeat/registry:/usr/share/filebeat/registry
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    networks:
    - efk-net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s

  # 初始帐号密码admin/admin
  grafana:
    image: grafana/grafana:latest
    volumes:
#      - /opt/efk/grafana/config:/etc/grafana
      - /opt/efk/grafana/data:/var/lib/grafana
      - /opt/efk/grafana/logs:/var/log/grafana
    environment:
      - cluster.name=efk-cluster
      # 安装插件
#      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - 3000:3000
    user: root
    networks:
      - efk-net

networks:
  efk-net:
