version: "3"

networks:
  sm-net:
    external: true

services:
  nacos:
    image: nacos/nacos-server:latest
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    - SPRING_DATASOURCE_PLATFORM=mysql
    - MYSQL_MASTER_SERVICE_HOST=db
    - MYSQL_MASTER_SERVICE_DB_NAME=nacos_config
    - MYSQL_MASTER_SERVICE_PORT=3306
    - MYSQL_SLAVE_SERVICE_HOST=mysql
    - MYSQL_SLAVE_SERVICE_PORT=3306
    - MYSQL_MASTER_SERVICE_USER=root
    - MYSQL_MASTER_SERVICE_PASSWORD=123456
    volumes:
    - /opt/nacos/logs/:/home/nacos/logs
    - /opt/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
    - "8848:8848"
    - "9555:9555"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
    - sm-net