version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
#      - /opt/x/nginx.conf:/etc/nginx/nginx.conf
      - /opt/x/html:/usr/share/nginx/html
#      - /opt/x/logs:/var/log/nginx
    deploy:
      replicas: 1
