version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.3.1
    environment:
      ES_JAVA_OPTS: '-Xms1048m -Xmx1048m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
      cluster.name: elk-cluster
    volumes:
      - /opt/elk/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.elasticsearch == 1]

  kibana:
    image: kibana:7.3.1
    networks:
      - elk-net
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
      cluster.name: elk-cluster
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.3.1
    volumes:
#    - /opt/elk/config/logstash/:/usr/share/logstash/config/
    - /opt/elk/config/logstash/:/usr/share/logstash/pipeline/
    - /opt/elk/build:/opt/build
    networks:
      - elk-net
    environment:
      cluster.name: elk-cluster
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.logstash == 1]
    ports:
      - "5001:5000"

#  logspout:
#    image: bekt/logspout-logstash
#    environment:
#      ROUTE_URIS: 'logstash+tcp://10.0.10.25:5001'
#    depends_on:
#      - logstash
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - elk-net
#    deploy:
#      mode: global
#      restart_policy:
#        condition: on-failure
#        delay: 30s

  logspout:
    image: bekt/logspout-logstash
    environment:
      ROUTE_URIS: 'logstash+tcp://logstash:5001'
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk-net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s

  grafana:
    image: grafana/grafana:latest
    volumes:
      - /opt/elk/grafana/data1:/var/lib/grafana
    container_name: grafana
    hostname: grafana
    environment:
      cluster.name: elk-cluster
    ports:
      - 3000:3000
    networks:
      - elk-net

networks:
  elk-net:
