version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.3.1
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      #- bootstrap.memory_lock=true
      # 测试开发时开启此配置，避免磁盘告警导致无法启动
      - cluster.routing.allocation.disk.threshold_enabled=false
      # 集群名称
      - cluster.name=elk-cluster
      # 节点名称
      - node.name=elasticsearch
      # cluster.initial_master_nodes 和 discovery.zen.ping.unicast.hosts 二选一
      # 初始主节点，多个节点以英文逗号分隔
      - cluster.initial_master_nodes=elasticsearch
      #- discovery.zen.ping.unicast.hosts=elasticsearch
      # 开启http访问
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    volumes:
      - /opt/x/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk-net
    deploy:
      mode: replicated
      replicas: 1
#      resources:
#        limits:
#          memory: 1g
      placement:
        constraints:
          - node.labels.elasticsearch == 1

  kibana:
    image: kibana:7.3.1
    volumes:
#      - /opt/x/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /opt/x/kibana/data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_REQUESTTIMEOUT=90000
      - XPACK_SECURITY_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - cluster.name=elk-cluster
    ports:
      - 5601:5601
    networks:
      - elk-net
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.3.1
    volumes:
#      - /opt/x/logstash/config/:/usr/share/logstash/config/
      - /opt/x/logstash/pipeline/:/usr/share/logstash/pipeline/
#      - /opt/x/logstash/data/:/usr/share/logstash/data/
#      - /opt/x/logstash/plugins/:/usr/share/logstash/plugins/
    environment:
      - cluster.name=elk-cluster
    ports:
      - 5000:5000
      - 5044:5044
    networks:
      - elk-net
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.logstash == 1

#  logspout:
#    image: bekt/logspout-logstash
#    environment:
#      ROUTE_URIS=logstash+tcp://10.0.10.25:5001'
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - elk-net
#    depends_on:
#      - logstash
#    deploy:
#      mode: global
#      restart_policy:
#        condition: on-failure
#        delay: 30s

  logspout:
    image: bekt/logspout-logstash
    environment:
      - ROUTE_URIS=logstash+tcp://logstash:5000
#      - ROUTE_URIS=logstash+udp://logstash:5000
#      - ROUTE_URIS=logstash://logstash:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk-net
    depends_on:
      - logstash
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s
        
#  filebeat:
#    image: prima/filebeat:6
#    volumes:
#      - /opt/x/filebeat/config/filebeat.yml:/filebeat.yml
#      - /opt/x/filebeat/data:/data
#      - /var/lib/docker/containers:/var/lib/docker/containers
#    networks:
#      - elk-net
#    deploy:
#      mode: global
#      restart_policy:
#        condition: on-failure
#        delay: 30s

  # 初始帐号密码admin/admin
  grafana:
    image: grafana/grafana:latest
    volumes:
#      - /opt/x/grafana/config:/etc/grafana
      - /opt/x/grafana/data:/var/lib/grafana
      - /opt/x/grafana/logs:/var/log/grafana
    environment:
      - cluster.name=elk-cluster
      # 安装插件
#      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - 3000:3000
    networks:
      - elk-net

networks:
  elk-net:
