version: '3.1'

networks:
  sm-net:
    external: true

services:
  redis:
    image: redis:5
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /opt/redis/logs:/logs
      - /opt/redis/data:/data
    networks:
      - sm-net

